CREATE TABLE locations (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           latitude DOUBLE PRECISION NOT NULL,
                           longitude DOUBLE PRECISION NOT NULL,

                           CONSTRAINT chk_locations_latitude
                               CHECK (latitude >= -90 AND latitude <= 90),

                           CONSTRAINT chk_locations_longitude
                               CHECK (longitude >= -180 AND longitude <= 180)
);

CREATE TABLE incidents (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           description TEXT NOT NULL,
                           severity VARCHAR(20) NOT NULL,
                           status VARCHAR(40) NOT NULL,
                           location_id BIGINT NOT NULL,
                           created_at TIMESTAMP NOT NULL,

                           CONSTRAINT fk_incidents_location
                               FOREIGN KEY (location_id)
                                   REFERENCES locations(id),

                           CONSTRAINT chk_incidents_severity
                               CHECK (severity IN ('CRITICAL', 'HIGH', 'MEDIUM', 'LOW')),

                           CONSTRAINT chk_incidents_status
                               CHECK (
                                   status IN (
                                              'REPORTED',
                                              'ASSESSED',
                                              'REQUIREMENTS_DETERMINED',
                                              'RESPONSE_IN_PROGRESS',
                                              'RESOLVED'
                                       )
                                   )
);


CREATE TABLE resources (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           type VARCHAR(30) NOT NULL,
                           status VARCHAR(20) NOT NULL,
                           location_id BIGINT NOT NULL,

                           CONSTRAINT fk_resources_location
                               FOREIGN KEY (location_id)
                                   REFERENCES locations(id),

                           CONSTRAINT chk_resources_type
                               CHECK (type IN ('AMBULANCE', 'FIRE_UNIT', 'RESCUE_TEAM')),

                           CONSTRAINT chk_resources_status
                               CHECK (status IN ('AVAILABLE', 'BUSY', 'OFFLINE', 'MAINTENANCE'))
);


CREATE TABLE response_teams (
                                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                status VARCHAR(20) NOT NULL,

                                CONSTRAINT chk_response_teams_status
                                    CHECK (status IN ('AVAILABLE', 'BUSY', 'OFFLINE', 'MAINTENANCE'))
);

CREATE TABLE capabilities (
                              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              name VARCHAR(50) NOT NULL UNIQUE,

                              CONSTRAINT chk_capabilities_name
                                  CHECK (
                                      name IN (
                                               'MEDICAL_RESPONSE',
                                               'FIRE_RESPONSE',
                                               'RESCUE_OPERATION'
                                          )
                                      )
);

CREATE TABLE resource_capabilities (
                                       resource_id BIGINT NOT NULL,
                                       capability_id BIGINT NOT NULL,

                                       PRIMARY KEY (resource_id, capability_id),

                                       CONSTRAINT fk_resource_capabilities_resource
                                           FOREIGN KEY (resource_id)
                                               REFERENCES resources(id),

                                       CONSTRAINT fk_resource_capabilities_capability
                                           FOREIGN KEY (capability_id)
                                               REFERENCES capabilities(id)
);


CREATE TABLE team_capabilities (
                                   team_id BIGINT NOT NULL,
                                   capability_id BIGINT NOT NULL,

                                   PRIMARY KEY (team_id, capability_id),

                                   CONSTRAINT fk_team_capabilities_team
                                       FOREIGN KEY (team_id)
                                           REFERENCES response_teams(id),

                                   CONSTRAINT fk_team_capabilities_capability
                                       FOREIGN KEY (capability_id)
                                           REFERENCES capabilities(id)
);


CREATE TABLE dispatches (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            incident_id BIGINT NOT NULL,
                            resource_id BIGINT NOT NULL,
                            response_team_id BIGINT,
                            status VARCHAR(20) NOT NULL,
                            created_at TIMESTAMP NOT NULL,

                            CONSTRAINT fk_dispatches_incident
                                FOREIGN KEY (incident_id)
                                    REFERENCES incidents(id),

                            CONSTRAINT fk_dispatches_resource
                                FOREIGN KEY (resource_id)
                                    REFERENCES resources(id),

                            CONSTRAINT fk_dispatches_response_team
                                FOREIGN KEY (response_team_id)
                                    REFERENCES response_teams(id),

                            CONSTRAINT chk_dispatches_status
                                CHECK (status IN ('CREATED', 'IN_PROGRESS', 'COMPLETED'))
);